# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{net-irc-mala}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kimoto"]
  s.date = %q{2012-02-10}
  s.default_executable = %q{mig.rb}
  s.description = %q{mala following API IRC Gateway}
  s.email = %q{sub+peerler@gmail.com}
  s.executables = ["mig.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/net-irc-mala.rb",
     "test/net-irc-mala_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/kimoto/net-irc-mala}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{mala following API IRC Gateway}
  s.test_files = [
    "test/test_helper.rb",
     "test/net-irc-mala_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<net-irc>, [">= 0"])
      s.add_runtime_dependency(%q<em-eventsource>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<net-irc>, [">= 0"])
      s.add_dependency(%q<em-eventsource>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<net-irc>, [">= 0"])
    s.add_dependency(%q<em-eventsource>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end
